
# Update to node:18 instead of node:18-alpine
FROM node:18 As development

# Required for Prisma Client to work in container
RUN apt-get update && apt-get install -y openssl

WORKDIR /app
# Copy application dependency manifests to the container image.
# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
COPY --chown=node:node package*.json ./

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

COPY --chown=node:node . .

RUN chmod -R 777 ./node_modules

# Use the node user from the image (instead of the root user)
USER node

CMD [  "npm", "run", "start:migrate:dev" ]